re-commit, find arduino bsp install path.

diff --git a/.github/workflows/Arduino-bsp.yml b/.github/workflows/Arduino-bsp.yml
--- a/.github/workflows/Arduino-bsp.yml
+++ b/.github/workflows/Arduino-bsp.yml
@@ -75,10 +75,11 @@ jobs:
           # 查詢核心資訊並解析 JSON 輸出，找到 'install_dir'
           CORE_PATH=$(arduino-cli core list --json | jq -r ".[] | select(.id == \"${CORE_NAME}\") | .installed_paths[] | select(.key == \"install_dir\") | .value")
 
-          if [ -z "$CORE_PATH" ]; then
-            echo "Error: Could not find install path for core ${CORE_NAME}"
-            exit 1
-          fi  
+          echo "core path = ${CORE_PATH}"
+          #if [ -z "$CORE_PATH" ]; then
+          #  echo "Error: Could not find install path for core ${CORE_NAME}"
+          #  exit 1
+          #fi  
       
       - name: List library example(NVT)
         shell: bash 
